extends: airbnb
env:
  browser: true
  node: true
  es6: true
parserOptions:
  sourceType: module
  ecmaVersion: 7
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
plugins:
  - react
  - jsx-a11y
  - import
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
      paths:
        - /src
      moduleDirectory:
        - node_modules
        - src
globals:
  __CLIENT__: false
  __SERVER__: false
  __DEV__: false
  __PROD__: false
  __DEBUG__: false
  webpackIsomorphicTools: false
rules:
  semi: [2, "never"]
  comma-dangle: [1, "never"]
  no-underscore-dangle: off
